### ISSUE TITLE
Empty API doc pages

### ISSUE THREAD

**Issue by ajjackson** [WMD-group/SMACT#10]
Visiting the API docs there seem to be some empty pages like http://smact.readthedocs.io/en/latest/smact.builder.html . We should probably add some docstrings to those modules!

**Comment by dandavies99** [comment]
I am seeing the same error as above again for the oxidation_states module, resulting in a blank docs page. @ajjackson, I'm not entirely sure on how you fixed this last time.

**Comment by dandavies99** [comment]
Sorted. Needed to add pymatgen to mock modules in docs/conf.py.
