### ISSUE TITLE
Tests failing on all dependabot branches

### ISSUE THREAD

**Issue by AntObi** [WMD-group/SMACT#142]
All of the dependabot pull requests to upgrade the package requirements for SMACT are failing the Github actions tests.
Running the tests locally on these branches appear to be working.

Will try to fully replicate locally to determine the problem.

**Comment by dandavies99** [comment]
Looks like Pydantic has been updated recently to V2, introducing some breaking changes: https://github.com/pydantic/pydantic/releases 

Pydantic 2.x is being installed in the latest CI runs, maybe we could pin to `pydantic<2`.

**Comment by AntObi** [comment]
@dandavies99 Yep, I've been able to replicate the errors by installing `pydantic==2.*`.
Will pin `pydantic==1.*` to the requirements.
