### ISSUE TITLE
Contributing section

### ISSUE THREAD

**Issue by dandavies99** [WMD-group/SMACT#18]
We currently have development notes in the readme 👍 but I think we could do with updating it and making it more obvious how people can contribute.

**Comment by dandavies99** [comment]
I've now updated this, are any additional changes needed?

**Comment by ajjackson** [comment]
That should do the job! It is standard to put this information in a CONTRIBUTING file, but given the short length of both this paragraph and the README in general it does seem cleaner to have it in the README for now.
