### ISSUE TITLE
Some examples are python2 only

### ISSUE THREAD

**Issue by zhubonan** [WMD-group/SMACT#30]
Some tutorials use scripts that can only be run with Python2. For example, those in `ELS_practical.ipynb`. 

At least, the following files are not Python3 compatible: 

>examples/Counting/ElementCombinationsParallel.py
>examples/Practical_tutorial/Electronic/scan_energies.py
>examples/Practical_tutorial/Lattice/LatticeMatch.py
>examples/Practical_tutorial/Site/csl.py
>examples/Practical_tutorial/Site/LatticeSite.py
>examples/Practical_tutorial/Site/surface_points.py

**Comment by keeeto** [comment]
A very good point - thanks for raising it. 
@dandavies99 @ajjackson - what do with think for this - I think I wrote the majority of these eg `LatticeMatch` and `csl` etc. I actually think that they fall outside the `smact` sphere these days. They date back to a time when the project was a lot less focussed. Should we consider removing some of these?
