### ISSUE TITLE
Bug in the allowed oxidation states of element Ir

### ISSUE THREAD

**Issue by usccolumbia** [WMD-group/SMACT#31]
the pymatgen and Wiki says Ir element has the following oxidation states
(-3, -1, 1, 2, 3, 4, 5, 6)
and common ones:
(3, 4)
https://en.wikipedia.org/wiki/Oxidation_state#cite_note-99

However, your smact reports the following 
[-2, -1, 1, 2, 3, 4, 5, 6, 7, 8] ------> is this -2 a. typo of. -3?      
and common ones:
[3, 4, 5, 6]

------> is this allowed -2 a. typo of. -3?      

This error causes mistakes in charge neutrality check.

**Comment by keeeto** [comment]
Thanks @usccolumbia - this issue is being addressed in pull request #33

**Comment by keeeto** [comment]
Closed by #33
