### ISSUE TITLE
Can the upper pin on pymatgen be removed?

### ISSUE THREAD

**Issue by CompRhys** [WMD-group/SMACT#316]
https://github.com/WMD-group/SMACT/blob/62079a3ee3829b4fc54cedfb56ab5e66d603e644/setup.py#L57

Currently there is a pin on the most recent pymatgen version that can be used, is this necessary at this point? If so can I assist in any way to fix the incompatibility?

**Comment by AntObi** [comment]
Hi @CompRhys, I believe I originally set that pin due to materialsproject/pymatgen#3990 causing the SMACT CI to fail on Windows. As that's been resolved, I can remove the pin. Will make that update shortly.

**Comment by AntObi** [comment]
@CompRhys Completed in #318
