### ISSUE TITLE
another outdated oxidation states for B

### ISSUE THREAD

**Issue by usccolumbia** [WMD-group/SMACT#36]
according to wiki (who cited literature for the negative oxidation states for B)
−5 |   |   |   | −1 | 0 | +1 | +2 | +3
-- | -- | -- | -- | -- | -- | -- | -- | --

Your table only has +1 +2 +3
which prevents your screening code to find  B6S, a new material. reported recently in https://www.nature.com/articles/s41598-020-66316-y

**Comment by keeeto** [comment]
Will keep an eye on this when we think about updating ox states. See response to #37 for how to do this yourself.

**Comment by dandavies99** [comment]
The [ICSD set of oxidation states](https://github.com/WMD-group/SMACT/blob/master/smact/data/oxidation_states_icsd.txt) includes `B -3 -2 -1 1 2 3`.  I don't think the evidence for B-5 is very strong. There are still no instances of it in the ICSD so it would not be appropriate to add it to the smact ICSD set.
