### ISSUE TITLE
pymatgen (v2022.0.*) is no longer backwards compatible

### ISSUE THREAD

**Issue by AntObi** [WMD-group/SMACT#42]
Some aspects of smact, particularly the structure prediction module depend on pymatgen which has now produced a backwards incompatible change which means that SMACT needs to either:

- Update all uses of pymatgen in SMACT to compatible with v.2022.0
-  Ensure when installing Smact that you use pymatgen==2021.*.*

More details about the announcement for pymatgen can be found in the link below:

[major announcement (v2022.0.*)](
https://pymatgen.org/#major-announcement-v2022-0)

**Comment by keeeto** [comment]
The fixes proposed in the `pymatgen` docs _seem_ simple enough. I would propose making a test branch, implementing those changes and testing the performance. I don't particularly like the idea of pinning to a legacy version, as this is inevitably a ticking time-bomb.
