### ISSUE TITLE
how to use SMACT to generate new random compositions?

### ISSUE THREAD

**Issue by usccolumbia** [WMD-group/SMACT#49]

**Comment by ajjackson** [comment]
If you have a look at the example notebooks, e.g. Counting/Generate_compositions_lists.ipynb filters over a complete set of combinations using `itertools.combinations(els, 2)`.

If you would like to replace an exhaustive search with random sampling, consider using `random.choices` instead, e.g.

```python
import random
from smact import element_dictionary, ordered_elements

# Say we are just interested in first row transition metals
all_el = element_dictionary()
els = [all_el[symbol] for symbol in ordered_elements(21,30)]

random_metal_pairs = [random.sample(els, 2) for _ in range(10)]
```
will generate a list of ten random combinations from the the first-row transition metals.
