### ISSUE TITLE
Using of neutral_ratios() method in the case of non-stoichiometric compounds.

### ISSUE THREAD

**Issue by FedeOtto** [WMD-group/SMACT#50]
Hello, as I'm dealing with non-stoichiometric compounds in my dataset, like `Hg 0.7 Cd 0.3 Te 1`, I'm wondering if there is any way I can use `neutral_ratios()` function to return acceptable ratios for having charge-balanced composition.

In the above case, for example `Hg` and `Cd` have both oxidation number `+2` while `Te` has oxidation number `+1`

I would need this to eventually check stability of inorganic compounds that I generate from my Machine Learning models, that in most cases may be non-stoichiometric.

**Comment by AntObi** [comment]
Hello, based off the oxidation states that you have suggested for your compound, the `neutral_ratios()` function would not return acceptable ratios as all the positive oxidation numbers would not be able to be charge balanced.

Currently, the function is built to deal with integer stoichiometric ratios, so a workaround would be to find the lowest integer stoichiometric ratio for your compound of interest, for example, `Hg 7 Cd 3 Te 10`. Then you could apply the `neutral_ratios()` function.

**Comment by keeeto** [comment]
I think that @AntObi has give a clear answer here. Potentially something to think about in future though.
