### ISSUE TITLE
Any special considerations for superconductors?

### ISSUE THREAD

**Issue by sgbaird** [WMD-group/SMACT#56]
Wondering if I should be able to use this out-of-the-box for superconducting materials or if I should downselect the filters (e.g. only using charge neutrality).

@cseeg

**Comment by keeeto** [comment]
We don't have any specific filters for give materials applications. Are you thinking of something like a template formaula for Cuperate SCs or something like that?
It mighbe nice to start having a set of flexible templates for common search spaces.

**Comment by cseeg** [comment]
Right now we have compositions with predicted critical temperature. That would be nice to have templates for different superconductor material classes though.

**Comment by keeeto** [comment]
Thanks for the motivation @cseeg - I have added the tag enhancement to this. I hope that the development team can have one of our SmactDown events in the near future, where we can review requests and ideas for future features and start working on the next round of updates. Ideas like this are most welcome!

**Comment by AntObi** [comment]
Closing this as partial solution linked in #76
