### ISSUE TITLE
How to use Smact to detect invalid covalent compounds?

### ISSUE THREAD

**Issue by usccolumbia** [WMD-group/SMACT#58]
Covalent compounds are formed by non-metal elements. but Not all non-metal element compositions are valid covalent comounds.
Is there any rules to declare a compound is NOT  covalent compound for sure?

**Comment by aronwalsh** [comment]
Closing this issue as it is connected to https://github.com/WMD-group/SMACT/issues/57. It is beyond current SMACT functionality but custom chemical filters are of course possible
