### ISSUE TITLE
oxidation states model not findable from paper

### ISSUE THREAD

**Issue by dandavies99** [WMD-group/SMACT#66]
The data access statement of the Faraday Discussion paper [Materials discovery by chemical analogy: role of oxidation states in structure prediction](https://pubs.rsc.org/en/content/articlelanding/2018/fd/c8fd00032h) directs people to the [examples folder](https://github.com/WMD-group/SMACT/tree/master/examples) but the oxidation states model has been moved into the [main SMACT code](https://github.com/WMD-group/SMACT/blob/master/smact/oxidation_states.py). 

We should add at least a minimal example in the examples folder showing the oxidation states model being used.

**Comment by AntObi** [comment]
I've created an example notebook which shows both simple usage of the oxidation states model and an attempt to replicate the results from the paper. #68
