### ISSUE TITLE
Running examples from a browser

### ISSUE THREAD

**Issue by AntObi** [WMD-group/SMACT#67]
Do we feel that there'd be any benefit to making our SMACT examples available to run in a browser using binder (https://mybinder.org) and/or colab (https://colab.research.google.com)?

The main inspiration for this thought was the Materials Virtual Lab notebooks (https://github.com/materialsvirtuallab/matgenb) and I think it could make some of the examples more accessible to use.

**Comment by dandavies99** [comment]
I think that would be cool. We used binder for surfaxe: https://github.com/SMTG-UCL/surfaxe but I personally prefer colab, although I've never set it up myself.
