### ISSUE TITLE
Suggested Refactoring Of __init__.py

### ISSUE THREAD

**Issue by JMSkelton** [WMD-group/SMACT#7]
Two suggestions for refactoring the current code base:

1. Move screening tests out of `__init__` and into their own `screening` submodule.

2. Possibly move the `Lattice` and `Site` classes, along with any associated "core" functions, from `lattice` into `__init__`.

Importing `smact` would provide access to the core classes used by the other submodules, along with a small number of related functions such as those for populating a list with all the elements of the periodic table. Most submodules would only need to import the parent `smact` module as a dependency.

The `screening` submodule would provide access to a collection of convenience functions for screening, which could be expanded regularly as new use cases arise.

The primary motivation is to bundle code which is likely to change regularly into discrete submodule(s).

A secondary motivation is one of semantics:

`import smact;
element = smact.Element('H');`

is a standard idiom for using classes, whereas

`from smact.screening import pauling_test; if pauling_test(...): ... ;`

would be a more "Pythonic" way to import a subset of screening functions for use in a script.

**Comment by keeeto** [comment]
I can't see any reason to oppose these changes. My one question is timing. Do we do it now and have it in place for the release? This would involve changing all scripts used so far. I don't actually think that is such a big deal.

**Comment by ajjackson** [comment]
I agree with @JMSkelton that importing functions from modules and classes from core looks more idiomatic (minus the semicolons :tongue: ).

It is worth mentioning the original motivation for this structure, which was to compartmentalise the "phases" of work with SMACT by module. I don't think this would be horribly undermined, and there is something to be said for emphasising `screening` as a phase of work.

As long as the tests are working I'm not too worried about script breakage at this stage. We don't have a release version yet; when we do, scripts can target a major release. For now the main thing is that the examples and tests _in the repository_ are updated with any API changes.

(Re: release numbers, here's a [very short article](http://www.sitepoint.com/semantic-versioning-why-you-should-using) about "SemVer" or Semantic Versioning. It has its critics, but it's a lot better than nothing.)

**Comment by ajjackson** [comment]
I will do this as I am working on the Pauling test anyway

**Comment by ajjackson** [comment]
For now I'm leaving the "charge_neutrality" code in __init__ as it revolves around generating lists of things rather than screening them. I'm renaming the functions to variants on "neutral_ratios" though, which I think is a more intuitive description of what they do

**Comment by ajjackson** [comment]
Done
