### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by keeeto** [WMD-group/SMACT#8]
Expand the test suite coverage of the code.

**Comment by dandavies99** [comment]
Can we also move/remove:
- Example_distort.py
- Example_surface.py
- ValenceMaxTest.py
from smact/tests? These appear to be examples as opposed to tests. I suggest create versions of example_distort and ValenceMaxTest in "examples" and remove Example_surface altogether.

**Comment by keeeto** [comment]
I think that these are out of date entirely. Suggest we remove them entirely.

**Comment by dandavies99** [comment]
That sounds easier

**Comment by keeeto** [comment]
:scorched_earth:

**Comment by dandavies99** [comment]
We have some good example tests in `tests/test.py`. We need to expand the coverage. At a glance, we can now add tests for:
- [ ] `oxidation_states` module (@dandavies99) 
- [ ] `data_loader` module 
- [ ] At least one test that checks, for a given stoichiometry threshold, a combination of elements results in the right number of neutral ratios being returned.

Can we get Travis to measure test coverage and help us spot what else needs adding?

**Comment by ajjackson** [comment]
Yup, by using another service called Coveralls. You have to register with coveralls and then add a few lines to the Travis setup. https://docs.travis-ci.com/user/coveralls/
Here's the Travis file for Galore: https://github.com/SMTG-UCL/galore/blob/master/.travis.yml

**Comment by dandavies99** [comment]
The original issue of expanding the test suite coverage has been achieved and we have continuous testing integration with Travis.
