### ISSUE TITLE
Include data from Faraday Oxidation Model

### ISSUE THREAD

**Issue by keeeto** [WMD-group/SMACT#9]
The model for likelihood of a given oxidation state in a given chemistry was developed in our Faraday Discussions paper: [Materials Discovery by Chemical Analogy: Role of Oxidation States in Structure Prediction](http://pubs.rsc.org/en/content/articlehtml/2018/fd/c8fd00032h)

The resultant data table from this study should be included in `SMACT`.

**Comment by keeeto** [comment]
@dandavies99 @ajjackson it's probably worth thinking a bit about how this gets included. The data is certainly not available for every species. 

I suppose that we can always have it set to False unless the information is available.

**Comment by ajjackson** [comment]
There's something to be said for raising an error; that will stop people trying to use it in a combinatorial search with unsupported elements?

**Comment by keeeto** [comment]
That's a good point. 

 I feel like we are at a point whereby we have several descriptors that are only partly available. Is it worth having a function that can quickly check the starting set of elements and make sure that they have all parameters/features that we will want to use eventually?

**Comment by dandavies99** [comment]
This model has been implemented in the `oxidationstates` module and merged into master. The last thing to do is add specific tests but we can cover that separately in #8 .
